# Generated by Django 3.0.5 on 2020-04-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200420_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestocourse',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='api.Course'),
        ),
    ]
