# Generated by Django 3.0.5 on 2020-05-08 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
